name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use your preferred Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./web

      # Run the build process
      - name: Build the project
        run: npm run build
        working-directory: ./web

      # Deploy generated build files (Commit to a specific branch)
      - name: Deploy build files
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add ./build
          git commit -m "Deploy build files"
          git push origin main