name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use Node.js 18 or a compatible version

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./web

      # Run the build process
      - name: Build the project
        run: npm run build
        working-directory: ./web